---
- name: Update apt cache
  apt: update_cache=yes

- name: Add the PostgreSQL APT key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add the PostgreSQL APT repositories
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
    state: present

- name: Update apt cache
    apt: update_cache=yes

- name: Install PostgreSQL
  apt:
    name: postgresql-{{ postgresql_version }}
    state: present
    
- name: Start and enable service
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true